# Generated by Django 4.2 on 2024-02-12 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('volunteer_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('permanentAddress', models.TextField(max_length=1000)),
                ('present_address', models.TextField(max_length=1000)),
                ('profession', models.CharField(max_length=100)),
                ('running_degree', models.TextField(blank=True, max_length=400, null=True)),
                ('leftest_degree', models.TextField(max_length=400)),
                ('passing_year', models.CharField(max_length=100)),
                ('institute', models.TextField(blank=True, max_length=400, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('other_description', models.TextField(blank=True, max_length=400, null=True)),
                ('blood_group', models.CharField(max_length=100)),
                ('previous_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_duty', models.TextField(blank=True, max_length=100, null=True)),
                ('present_organization', models.CharField(max_length=100)),
                ('interested_charity_work', models.TextField(max_length=3000)),
            ],
        ),
    ]
