# Generated by Django 4.2 on 2024-02-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
