# Generated by Django 4.2 on 2024-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
