# Generated by Django 4.2.3 on 2024-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_review_alter_aboutactivity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
