# Generated by Django 4.2.3 on 2024-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0004_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disastermanagementwig',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wing/Disaster'),
        ),
        migrations.AddField(
            model_name='educationwing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wing/Education'),
        ),
        migrations.AddField(
            model_name='medicalwings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wing/medical'),
        ),
    ]
