# Generated by Django 4.2 on 2024-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtName', models.CharField(blank=True, max_length=100, null=True)),
                ('policeStation', models.CharField(blank=True, max_length=100, null=True)),
                ('campDate', models.CharField(blank=True, max_length=100, null=True)),
                ('hostName', models.CharField(blank=True, max_length=100, null=True)),
                ('Org_reg_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('org_est_date', models.CharField(blank=True, max_length=100, null=True)),
                ('org_total_Member', models.CharField(blank=True, max_length=10, null=True)),
                ('org_active_Members', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.TextField(blank=True, max_length=5000, null=True)),
                ('incidental_camp', models.CharField(max_length=100)),
                ('incidental_camp_longTerm', models.TextField(blank=True, null=True)),
                ('before_medical_camp', models.CharField(max_length=100)),
                ('Long_term_work_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('Previous_Camp_Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Previous_Camp_with_whichOrg', models.CharField(blank=True, max_length=100, null=True)),
                ('regFee_per_person', models.CharField(blank=True, max_length=100, null=True)),
                ('include_local_diagnostic_center', models.CharField(blank=True, max_length=100, null=True)),
                ('include_local_farma', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_Patient', models.IntegerField(blank=True, null=True)),
                ('camp_Vanue', models.CharField(blank=True, max_length=100, null=True)),
                ('local_unionCouncil', models.CharField(blank=True, max_length=100, null=True)),
                ('police', models.CharField(blank=True, max_length=100, null=True)),
                ('local_community_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('local_upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_advanced_reg', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_patient_advanced_reg', models.CharField(blank=True, max_length=100, null=True)),
                ('provide_medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_of_spendMoney_for_medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('volunteer_attend_for_camp', models.IntegerField()),
                ('medical_team_want_to_take', models.CharField(blank=True, max_length=100, null=True)),
                ('volunterr_conduct', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_eat_Vanue', models.CharField(blank=True, max_length=100, null=True)),
                ('away_from_the_campsite', models.CharField(blank=True, max_length=100, null=True)),
                ('site_seeing_plans', models.CharField(blank=True, max_length=100, null=True)),
                ('spotName', models.CharField(blank=True, max_length=100, null=True)),
                ('one_night_accommodation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
