# Generated by Django 4.2 on 2024-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_medicalcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcamp',
            name='Food_hospitality_coordinator_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='Food_hospitality_coordinator_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='Food_hospitality_coordinator_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='blood_grouping',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='blood_pressure_check_up',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='chief_executive_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='chief_executive_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='chief_executive_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='communication_coordinator_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='communication_coordinator_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='communication_coordinator_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='decoration_discipline_coordinator_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='decoration_discipline_coordinator_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='decoration_discipline_coordinator_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='diabetes_checkup',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='ear_examination',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='ecg',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='event_management_coordinator_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='event_management_coordinator_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='event_management_coordinator_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='eye_examination',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='heart_lung_check_up',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='publicity_coordinator_facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='publicity_coordinator_mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='publicity_coordinator_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='pulse_check_up_blood_oxygen_measurement',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='ultrasonogram',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='urine_test',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='weight_height_measurement',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
