# Generated by Django 4.2 on 2024-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_medicalcamp_food_hospitality_coordinator_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcamp',
            name='blood_grouping',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='blood_pressure_check_up',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='diabetes_checkup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='ear_examination',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='eye_examination',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='heart_lung_check_up',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='pulse_check_up_blood_oxygen_measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='urine_test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcamp',
            name='weight_height_measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
